implement browse POST request
algolia/algoliasearch-client-scala pull request #621
Opened 2021-02-18 20:50 UTC by yawen-QvQ

As titled. This allows us to fetch items when query is very long.

2021-02-18 21:31 UTC, benwaffle commented
@Aallam can you review? Also, what do we think about just replacing the existing `browse` method to use POST instead of GET? Do you expect that to break anything?

2021-02-22 09:31 UTC, Aallam requested changes

2021-02-22 09:31 UTC, Aallam commented on src/test/scala/algolia/integration/BrowseIntegrationTest.scala
> +import scala.language.postfixOps
I think this can be removed?

2021-02-22 09:32 UTC, Aallam commented
Hi @benwaffle and @yawen-QvQ, thank you for your PR!
I don't expect this won't break anything, if we look at [Java client implementation](https://github.com/algolia/algoliasearch-client-java-2/blob/dccd04247b1b479f9e5eb0edbdb9e775861489dc/algoliasearch-core/src/main/java/com/algolia/search/SearchIndex.java#L1581), it uses POST and it works as expected.

2021-02-23 14:20 UTC, Aallam commented
I've created a fork of this PR (#622) to run the CI.

2021-02-23 14:20 UTC, closed without merging